version: '3'
services:

  ### Nginx container #########################################

  nginx:
      image: nginx:alpine
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html/:rw
        - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./services/nginx/conf.d:/etc/nginx/conf.d:ro
        - ./services/nginx/log:/var/log/nginx:rw
      restart: always
      privileged: true
      container_name: nginx
      networks:
        - net-php72

  ### PHP container #########################################

  php72:
      build:
        context: ./services/php72
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      volumes:
        - ${PROJECT_FOLDER}:/etc/nginx/html:rw
        - ./services/php72/config/php.ini:/usr/local/etc/php/php.ini:ro
        - ./services/php72/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
        - ./services/php72/log:/var/log:rw
      restart: always
      privileged: true
      container_name: php72
      networks:
        - net-php72
#        - net-mysql
        - net-redis

  ### Mysql container #########################################

#  mysql:
#      image: mysql:5.7
#      ports:
#        - "${MYSQL_PORT}:3306"
#      volumes:
#        - ./work/components/mysql/data:/var/lib/mysql:rw
#        - ./work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
#        - ./work/components/mysql/log:/var/log/mysql:rw
#      restart: always
#      privileged: true
#      environment:
#        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
#      networks:
#        - net-mysql

  ### Redis container #########################################

  redis:
      image: redis:latest
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
        - ./services/redis/log/redis.log:/var/log/redis/redis.log:rw
      restart: always
      privileged: true
      container_name: redis
      networks:
        - net-redis

  ### Tools container #########################################

#  tools:
#      build:
#        context: ./build/tools
#        args:
#          TIME_ZONE: ${GLOBAL_TIME_ZONE}
#          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
#      volumes:
#        - ./work/components/tools/start.sh:/home/start.sh:rw
#        - ./work/components/tools/backup:/backup:rw
#        - ./work/components/tools/cron.d:/etc/cron.d:rw
#      restart: always
#      privileged: true
#      networks:
#        - net-php
#        - net-mysql
#        - net-redis

networks:
  net-php72:
#  net-mysql:
  net-redis:
